/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.livingsmart.hdr;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 *  {@link OrderedItem} contains an {@link Item} and an amount of {@link Item}s of this type ordered
 * @author Pieter
 */
@Entity
@Table
public class OrderedItem implements Serializable 
{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @OneToOne
    private Item item;
    
    @ManyToOne
    @JsonIgnore
    private OrderBean order;
    
    @Column(name = "amount", nullable = false)
    private int amount;

    /**
     *  Returns an automatically generated {@link Long} 
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }

    /**
     *  Sets the id, this {@link Long} gets automatically generated by jpa
     * @param id    {@link Long}
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *  Returns the {@link Item} this {@link OrderedItem} is connected to
     * @return {@link Item}
     */
    public Item getItem() {
        return item;
    }

    /**
     *  Sets the {@link Item} this {@link OrderedItem} is connected to
     * @param item  {@link Item}
     */
    public void setItem(Item item) {
        this.item = item;
    }

    /**
     *  Returns an {@link Integer} for the amount of {@link Item}s this {@link OrderedItem} has
     * @return {@link Integer}
     */
    public int getAmount() {
        return amount;
    }

    /**
     *  Sets the amount of {@link Item}s this {@link OrderedItem} has
     * @param amount {@link Integer}
     */
    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     *  Returns the {@link OrderBean} this {@link OrderedItem} is connected to
     * @return  {@link OrderBean}
     */
    public OrderBean getOrder() {
        return order;
    }

    /**
     *  Returns the {@link OrderBean} this {@link OrderedItem} is connected to
     * @param order {@link OrderBean}
     */
    public void setOrder(OrderBean order) {
        this.order = order;
    }
    
    
    
    
}
